create table users(
id int8 not null generated by default as identity,
username varchar(255) null,
email varchar(255) null,
"password" varchar(255) null,
constraint users_pkey primary key (id)
);

create table merchant(
id int8 not null generated by default as identity,
merchant_name varchar(255) null,
merchant_location varchar(255) null,
"open" boolean null,
constraint merchant_pkey primary key (id)
);

create table product(
id int8 not null generated by default as identity,
product_name varchar(255) null,
price int8 null,
merchant_id int8 null,
constraint product_pkey primary key (id),
constraint merchant_id_constraint foreign key (merchant_id) references merchant(id)
);

create table "order"(
id int8 not null generated by default as identity,
order_time timestamp null,
destination_address varchar(255) null,
user_id int8 null,
completed boolean null,
constraint order_pkey primary key (id),
constraint user_id_constraint foreign key (user_id) references users(id)
);

create table order_detail(
id int8 not null generated by default as identity,
quantity int8 null,
total_price int8 null,
order_id int8 null,
product_id int8 null,
constraint order_detail_pkey primary key (id),
constraint order_id_constraint foreign key (order_id) references "order"(id),
constraint product_id_constraint2 foreign key (product_id) references product(id)
);

INSERT INTO public.users
(username, email, "password") values
('ferdy123', 'ferdy123@gmail.com', '123456'),
('novri123', 'novri123@gmail.com','admin123'),
('fariz234', 'fariz234@gmail.com','qwerty321');

INSERT INTO public.merchant
(merchant_name, merchant_location, "open") values
('Ayam KQ3', 'jaksel', true ),
('binargeprek', 'jakpus', true ),
('ferdykitchen', 'jakbar', false );

INSERT INTO public.product
(product_name, price, merchant_id) values
('ayam bakar', 15000, 1),
('ayam goreng', 13000, 1 ),
('ayam geprek keju', 18000, 2),
('dimsum ayam', 8000, 3),
('capcay daging', 25000, 3);

INSERT INTO public."order"
(order_time, destination_address, user_id, completed) values
(now(), 'bekasi', 1, true),
(now(), 'pondok bekasi', 1, false),
(now(), 'kranji', 2, true),
(now(), 'kranji', 3, true),
(now(), 'pondok kopi', 3, true);

INSERT INTO public.order_detail
(order_id, product_id, quantity, total_price) values
(1, 4, 5, 40000),
(1, 5, 1, 25000),
(2, 3, 1, 18000),
(3, 1, 2, 30000),
(4, 2, 1, 13000),
(5, 1, 1, 15000),
(5, 2, 1, 13000);

SELECT * FROM public.users u;
SELECT * FROM public.merchant m;
SELECT * FROM public.product p;
SELECT * FROM public."order" o ;
SELECT * FROM public.order_detail od ;

// Menampilkan daftar pesanan (order) dengan informasi pelanggan (users) dan alamat tujuan//

SELECT o.id AS order_id, u.username AS customer_username, o.destination_address
FROM public."order" o
JOIN public.users u ON o.user_id = u.id;

//Menampilkan daftar produk (product) beserta nama merchant dan harga produk//

SELECT p.product_name, m.merchant_name, p.price
FROM public.product p
JOIN public.merchant m ON p.merchant_id = m.id;

//Menampilkan rincian pesanan (order_detail) dengan informasi produk (product) yang dipesan//

SELECT od.id AS order_detail_id, p.product_name, od.quantity, od.total_price
FROM public.order_detail od
JOIN public.product p ON od.product_id = p.id;

//Menampilkan daftar pesanan (order) yang telah diselesaikan (completed) dengan informasi pelanggan (users), alamat tujuan, dan produk yang dipesan//

SELECT o.id AS order_id, u.username AS customer_username, o.destination_address, p.product_name, od.quantity, od.total_price
FROM public."order" o
JOIN public.users u ON o.user_id = u.id
JOIN public.order_detail od ON o.id = od.order_id
JOIN public.product p ON od.product_id = p.id
WHERE o.completed = true;